#!/usr/bin/perl

use strict;
use warnings;

BEGIN {
        my $default_cmd = "commands";
        # unshift @ARGV, $default_cmd unless $ARGV[0] =~ /^\w/;
}

use App::Math::Trainer;
my $app = App::Math::Trainer->new();
$app->run();

